### ISSUE TITLE
ISSUE: Banned from Coinchat

### ISSUE THREAD

**Issue by Vectrex33** [austinprog/FindYourYoutuber-NONGUI#14]
Austin, we will have to communicate some other way.

**Comment by austinprog** [comment]
Ok, :/ sorry you got banned man, um I guess this will be the official page for communication https://groups.google.com/forum/#!forum/funkyhuskyorganization

**Comment by Vectrex33** [comment]
Ok, requested membership.

**Comment by austinprog** [comment]
Membership approved
